- alias: "Reset Daily Egg Counts"
  trigger:
    - platform: time
      at: "00:00:00"
  action:
    - service: input_number.set_value
      data:
        value: 0
      target:
        entity_id:
          - input_number.white_eggs_daily
          - input_number.beige_eggs_daily
          - input_number.mint_eggs_daily
          - input_number.olive_eggs_daily
          - input_number.brown_eggs_daily
          - input_number.chocolate_eggs_daily
          - input_number.broken_eggs_daily

- alias: "Update Storage After Daily Collection"
  trigger:
    - platform: state
      entity_id:
        - input_number.white_eggs_daily
        - input_number.beige_eggs_daily
        - input_number.mint_eggs_daily
        - input_number.olive_eggs_daily
        - input_number.brown_eggs_daily
        - input_number.chocolate_eggs_daily
  action:
    - service: input_number.set_value
      target:
        entity_id: input_number.eggs_in_storage
      data:
        value: >-
          {{ states('input_number.eggs_in_storage')|float +
             trigger.to_state.state|float - trigger.from_state.state|float }}