input_number:
  white_eggs_daily:
    name: White Eggs Today
    min: 0
    max: 1000
    step: 1
    mode: box
  beige_eggs_daily:
    name: Beige Eggs Today
    min: 0
    max: 1000
    step: 1
    mode: box
  mint_eggs_daily:
    name: Mint Eggs Today
    min: 0
    max: 1000
    step: 1
    mode: box
  olive_eggs_daily:
    name: Olive Eggs Today
    min: 0
    max: 1000
    step: 1
    mode: box
  brown_eggs_daily:
    name: Brown Eggs Today
    min: 0
    max: 1000
    step: 1
    mode: box
  chocolate_eggs_daily:
    name: Chocolate Eggs Today
    min: 0
    max: 1000
    step: 1
    mode: box
  broken_eggs_daily:
    name: Broken Eggs Today
    min: 0
    max: 1000
    step: 1
    mode: box
  eggs_in_storage:
    name: Eggs in Storage
    min: 0
    max: 10000
    step: 1
    mode: box
  eggs_sold_quantity:
    name: Eggs Sold Quantity
    min: 0
    max: 1000
    step: 1
    mode: box
  eggs_sold_price:
    name: Price per Egg (€)
    min: 0
    max: 100
    step: 0.01
    mode: box
  eggs_used:
    name: Eggs Used
    min: 0
    max: 1000
    step: 1
    mode: box
  total_hens:
    name: Total Hens
    min: 0
    max: 1000
    step: 1
    mode: box
  total_roosters:
    name: Total Roosters
    min: 0
    max: 1000
    step: 1
    mode: box
  eggs_to_hatch:
    name: Eggs Set for Hatching
    min: 0
    max: 1000
    step: 1
    mode: box
  bought_eggs_to_hatch:
    name: Bought Eggs for Hatching
    min: 0
    max: 1000
    step: 1
    mode: box
  hatched_eggs:
    name: Successfully Hatched Eggs
    min: 0
    max: 1000
    step: 1
    mode: box
  hatched_hens:
    name: Hatched Hens
    min: 0
    max: 1000
    step: 1
    mode: box
  hatched_roosters:
    name: Hatched Roosters
    min: 0
    max: 1000
    step: 1
    mode: box

input_datetime:
  scratch_grain_purchase_date:
    name: Scratch Grain Purchase Date
    has_date: true
    has_time: true
  pellets_purchase_date:
    name: Pellets Purchase Date
    has_date: true
    has_time: true
  bedding_purchase_date:
    name: Bedding Purchase Date
    has_date: true
    has_time: true

input_text:
  scratch_grain_amount:
    name: Scratch Grain Amount (€)
    initial: "0.00"
  pellets_amount:
    name: Pellets Amount (€)
    initial: "0.00"
  bedding_amount:
    name: Bedding Amount (€)
    initial: "0.00"